### PR TITLE
Update app.d

### PR DESCRIPTION
**Pull request by aspenforest**
Refactored calculate_fertility to look and perform better and consolidate the magic numbers into an array for easier later modification.

### CODE REVIEW

**Comment by Master-Foo** [comment]
That's a good refactor. Thanks. I would have probably just moved on without ever touching this again.

**Comment by Master-Foo** [comment]
I'm not sure how interested you are in this project. But, you inspired me to go balls to the wall with the magic numbers thing. Now it's completely automated. No long list of if-else statements.

./total_fertility_rate.d

**Comment by aspenforest** [comment]
Your new version is miles better than the previous one, even better than my
refactor :P

**Comment by Master-Foo** [comment]
Thanks man, I felt kind of guilty wiping out your work, but your concept of using an array to simplify things was a good idea and it's still there. So, take some credit for yourself.

**Pull request merged**
